# Ignore Travis CI and Appveyor so accurate GPU coverage is reported by GitLab.
codecov:
  ci:
    - !appveyor
    - !travis

coverage:
  ignore:
    - "docs/*.jl"
    - "examples/*.jl"
    - "test/*.jl"
    - ".git/logs/refs/remotes/origin/*.jl" # hack to avoid coverage error in gitlab-ci; 
    
  status:
    project:
      default:
        target: auto
        threshold: 50
        base: auto

comment: false
