language: julia

os:
  - osx
  - linux

julia:
  - 0.7
  - 1.0
  - nightly

matrix:
  allow_failures:
    - julia: 1.0
    - julia: nightly

after_success:
  - julia -e 'using Pkg; ps=Pkg.PackageSpec(name="Documenter"); Pkg.add(ps); Pkg.dir("GeophysicalFlows"); include(joinpath("docs", "make.jl"))'
  - julia -e 'using Pkg; Pkg.add("Coverage"); Pkg.dir("GeophysicalFlows"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

notifications:
  email: true
